volumes:
    pg_data: {}

services:

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:alpine
    command: postgres -N 500 -c config_file=/home/app/postgresql.conf
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: benchbase
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./:/home/app
      - pg_data:/var/lib/postgresql/data
    working_dir: "/home/app"

